---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skate-app
  labels:
    app: webapp
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: nginx
          image: prachiii123/skate:1.0
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 50Mi
              cpu: 0.5m
            limits:
              memory: 100Mi
              cpu: 0.5m


